import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/components/navbar/navbar";
import Footer from "@/app/components/footer/footer";

const fontPoppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Milkaa",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${fontPoppins.variable} antialiased leading-8 overflow-x-hidden dark:bg-[#121212] dark:text-white transition-colors duration-500 ease-in-out`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
